# Build and deploy Next package
name: Deploy package

on: [push, pull_request]

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install packages
      run: npm ci

    - name: Build
      run: npm run build

    - uses: actions/upload-pages-artifact@v1.0.7
      with:
        path: "out/"

  deploy:
    needs: upload

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/deploy-pages@v1.2.4
